sudo: required
language: python
python: "3.6"

script:
  # Build the binary (.deb)
  - debuild -i -us -uc -b
  # Install the binary, running the debian scripts in the process
  - sudo apt install ../*.deb -y

  # Go through function tests
  - ./tests/importing.sh
  - ./tests/passthrough.sh
  - ./tests/pam.sh
  - ./tests/compare.sh

  # Remove howdy from the installation
  - sudo apt purge howdy -y

notifications:
  email:
    on_success: never
    on_failure: always

addons:
  apt:
    update: true
    packages:
      - dh-make
      - ack-grep
      - devscripts
      - fakeroot
      - pamtester
